/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;
import javax.swing.plaf.basic.BasicInternalFrameUI;
/**
 *
 * @author one
 */
public class Gpa_calculator extends javax.swing.JInternalFrame {

    /**
     * Creates new form Gpa_calculator
     */
    public Gpa_calculator() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui1 = (BasicInternalFrameUI)this.getUI();
        ui1.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelgpacal = new javax.swing.JPanel();
        jLabelgradecal = new javax.swing.JLabel();
        jLabelsubname1 = new javax.swing.JLabel();
        jLabelsubname2 = new javax.swing.JLabel();
        jLabelsubname3 = new javax.swing.JLabel();
        jLabelsubname4 = new javax.swing.JLabel();
        jLabelsubname5 = new javax.swing.JLabel();
        jLabelsubname6 = new javax.swing.JLabel();
        jTextFieldsubnam1 = new javax.swing.JTextField();
        jTextFieldsubnam2 = new javax.swing.JTextField();
        jTextFieldsubnam3 = new javax.swing.JTextField();
        jTextFieldsubnam4 = new javax.swing.JTextField();
        jTextFieldsubnam5 = new javax.swing.JTextField();
        jTextFieldsubnam6 = new javax.swing.JTextField();
        jTextFieldgrade1 = new javax.swing.JTextField();
        jTextFieldgrade2 = new javax.swing.JTextField();
        jTextFieldgrade3 = new javax.swing.JTextField();
        jTextFieldgrade4 = new javax.swing.JTextField();
        jTextFieldgrade5 = new javax.swing.JTextField();
        jTextFieldgrade6 = new javax.swing.JTextField();
        jTextFieldgpatotal = new javax.swing.JTextField();
        jTextFieldavggpa = new javax.swing.JTextField();
        jLabelgpaavg = new javax.swing.JLabel();
        jLabelgpatoal = new javax.swing.JLabel();
        jButtoncalculate = new javax.swing.JButton();
        jTextFieldshowgrade1 = new javax.swing.JTextField();
        jTextFieldshowgrade2 = new javax.swing.JTextField();
        jTextFieldshowgrade3 = new javax.swing.JTextField();
        jTextFieldshowgrade4 = new javax.swing.JTextField();
        jTextFieldshowgrade5 = new javax.swing.JTextField();
        jTextFieldshowgrade6 = new javax.swing.JTextField();
        jLabelsubname7 = new javax.swing.JLabel();
        jLabelsubname8 = new javax.swing.JLabel();
        jLabelsubname9 = new javax.swing.JLabel();

        jLabelgradecal.setBackground(new java.awt.Color(180, 180, 180));
        jLabelgradecal.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelgradecal.setText("Grade Calculater");

        jLabelsubname1.setBackground(new java.awt.Color(204, 204, 204));
        jLabelsubname1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelsubname1.setForeground(new java.awt.Color(102, 153, 255));
        jLabelsubname1.setText("Subject Name 1");

        jLabelsubname2.setBackground(new java.awt.Color(204, 204, 204));
        jLabelsubname2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelsubname2.setForeground(new java.awt.Color(102, 153, 255));
        jLabelsubname2.setText("Subject Name 2");

        jLabelsubname3.setBackground(new java.awt.Color(204, 204, 204));
        jLabelsubname3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelsubname3.setForeground(new java.awt.Color(102, 153, 255));
        jLabelsubname3.setText("Subject Name 3");

        jLabelsubname4.setBackground(new java.awt.Color(204, 204, 204));
        jLabelsubname4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelsubname4.setForeground(new java.awt.Color(102, 153, 255));
        jLabelsubname4.setText("Subject Name 4");

        jLabelsubname5.setBackground(new java.awt.Color(204, 204, 204));
        jLabelsubname5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelsubname5.setForeground(new java.awt.Color(102, 153, 255));
        jLabelsubname5.setText("Subject Name 5");

        jLabelsubname6.setBackground(new java.awt.Color(204, 204, 204));
        jLabelsubname6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelsubname6.setForeground(new java.awt.Color(102, 153, 255));
        jLabelsubname6.setText("Subject Name 6");

        jTextFieldsubnam1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldsubnam1.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldsubnam1.setText(" ");

        jTextFieldsubnam2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldsubnam2.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldsubnam2.setText(" ");

        jTextFieldsubnam3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldsubnam3.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldsubnam3.setText(" ");

        jTextFieldsubnam4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldsubnam4.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldsubnam4.setText(" ");

        jTextFieldsubnam5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldsubnam5.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldsubnam5.setText(" ");

        jTextFieldsubnam6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldsubnam6.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldsubnam6.setText(" ");

        jTextFieldgrade1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldgrade1.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldgrade1.setText(" ");

        jTextFieldgrade2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldgrade2.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldgrade2.setText(" ");

        jTextFieldgrade3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldgrade3.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldgrade3.setText(" ");

        jTextFieldgrade4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldgrade4.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldgrade4.setText(" ");

        jTextFieldgrade5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldgrade5.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldgrade5.setText(" ");

        jTextFieldgrade6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldgrade6.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldgrade6.setText(" ");

        jTextFieldgpatotal.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldgpatotal.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldgpatotal.setText(" ");

        jTextFieldavggpa.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldavggpa.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldavggpa.setText(" ");

        jLabelgpaavg.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelgpaavg.setText("Average");

        jLabelgpatoal.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelgpatoal.setText("GPA");

        jButtoncalculate.setBackground(new java.awt.Color(102, 204, 255));
        jButtoncalculate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButtoncalculate.setText("Calculate");
        jButtoncalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncalculateActionPerformed(evt);
            }
        });

        jTextFieldshowgrade1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldshowgrade1.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldshowgrade1.setText(" ");

        jTextFieldshowgrade2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldshowgrade2.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldshowgrade2.setText(" ");

        jTextFieldshowgrade3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldshowgrade3.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldshowgrade3.setText(" ");

        jTextFieldshowgrade4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldshowgrade4.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldshowgrade4.setText(" ");

        jTextFieldshowgrade5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldshowgrade5.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldshowgrade5.setText(" ");

        jTextFieldshowgrade6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextFieldshowgrade6.setForeground(new java.awt.Color(153, 204, 255));
        jTextFieldshowgrade6.setText(" ");

        jLabelsubname7.setBackground(new java.awt.Color(204, 204, 204));
        jLabelsubname7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelsubname7.setForeground(new java.awt.Color(102, 153, 255));
        jLabelsubname7.setText("Enter Subject Name ");

        jLabelsubname8.setBackground(new java.awt.Color(204, 204, 204));
        jLabelsubname8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelsubname8.setForeground(new java.awt.Color(102, 153, 255));
        jLabelsubname8.setText("Enter Num");

        jLabelsubname9.setBackground(new java.awt.Color(204, 204, 204));
        jLabelsubname9.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabelsubname9.setForeground(new java.awt.Color(102, 153, 255));
        jLabelsubname9.setText("Show Grades");

        javax.swing.GroupLayout jPanelgpacalLayout = new javax.swing.GroupLayout(jPanelgpacal);
        jPanelgpacal.setLayout(jPanelgpacalLayout);
        jPanelgpacalLayout.setHorizontalGroup(
            jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelgpacalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelgradecal, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(384, 384, 384))
            .addGroup(jPanelgpacalLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelgpacalLayout.createSequentialGroup()
                        .addComponent(jLabelsubname6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldsubnam6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelgpacalLayout.createSequentialGroup()
                        .addComponent(jLabelsubname5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldsubnam4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelgpacalLayout.createSequentialGroup()
                        .addComponent(jLabelsubname4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldsubnam5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelgpacalLayout.createSequentialGroup()
                        .addComponent(jLabelsubname3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldsubnam3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelgpacalLayout.createSequentialGroup()
                        .addComponent(jLabelsubname2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldsubnam2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelgpacalLayout.createSequentialGroup()
                        .addComponent(jLabelsubname1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelgpacalLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jTextFieldsubnam1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelgpacalLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabelsubname7)))))
                .addGroup(jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelgpacalLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldgrade1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldgrade2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldgrade3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldgrade4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldgrade5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldgrade6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelgpacalLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabelsubname8)))
                .addGap(31, 31, 31)
                .addGroup(jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelgpacalLayout.createSequentialGroup()
                        .addGroup(jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldshowgrade1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldshowgrade2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldshowgrade3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldshowgrade4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldshowgrade5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldshowgrade6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelgpacalLayout.createSequentialGroup()
                                .addComponent(jLabelgpatoal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelgpacalLayout.createSequentialGroup()
                                .addComponent(jLabelgpaavg, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelgpacalLayout.createSequentialGroup()
                                .addGroup(jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldavggpa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtoncalculate)
                                    .addComponent(jTextFieldgpatotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(129, 129, 129))))
                    .addGroup(jPanelgpacalLayout.createSequentialGroup()
                        .addComponent(jLabelsubname9)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelgpacalLayout.setVerticalGroup(
            jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelgpacalLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabelgradecal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelsubname7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelsubname8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelsubname9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelsubname1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldsubnam1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldgrade1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelgpaavg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldshowgrade1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelsubname2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldsubnam2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldgrade2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldavggpa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldshowgrade2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelgpacalLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelsubname3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldsubnam3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldgrade3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldshowgrade3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelsubname4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldsubnam5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldgrade4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldshowgrade4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelsubname5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldsubnam4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldgrade5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldshowgrade5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelsubname6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldsubnam6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldgrade6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldshowgrade6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelgpacalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jLabelgpatoal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldgpatotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButtoncalculate)
                        .addGap(76, 76, 76))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelgpacal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelgpacal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoncalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncalculateActionPerformed
        // TODO add your handling code here:
        String sub1,sub2,sub3,sub4,sub5,sub6;
        double average;
        double gpa =0.0;
        sub1 = jTextFieldgrade1.getText();
        sub2 = jTextFieldgrade2.getText();
        sub3 = jTextFieldgrade3.getText();
        sub4 = jTextFieldgrade4.getText();
        sub5 = jTextFieldgrade5.getText();
        sub6 = jTextFieldgrade6.getText();
        
        
                double subject1 = Double.parseDouble(sub1);
                double subject2 = Double.parseDouble(sub2);
                double subject3 = Double.parseDouble(sub3);
                double subject4 = Double.parseDouble(sub4);
                double subject5 = Double.parseDouble(sub5);
                double subject6 = Double.parseDouble(sub6);
        average =((subject1+subject2+subject3+subject4+subject5+subject6)/6);
        //subject1
        if (subject1>=80)
        {
            jTextFieldshowgrade1.setText("A");
            gpa =gpa+4.0;
        }
        else if(subject1>=65&&subject1<80)
        {
            jTextFieldshowgrade1.setText("B");
            gpa =gpa+3.0;
        }
        else if(subject1>=50&&subject1<65)
        {
            jTextFieldshowgrade1.setText("C");
            gpa =gpa+2.0;
        }
        else if(subject1>=40&&subject1<50)
        {
            jTextFieldshowgrade1.setText("D");
            gpa =gpa+1.0;
        }
        else if(subject1<40)
        {
            jTextFieldshowgrade1.setText("F");
            gpa =gpa+0.0;
        }
        //sub2
        
        if (subject2>=80)
        {
            jTextFieldshowgrade2.setText("A");
            gpa =gpa+4.0;
        }
        else if(subject2>=65&&subject2<80)
        {
            jTextFieldshowgrade2.setText("B");
            gpa =gpa+3.0;
        }
        else if(subject2>=50&&subject2<65)
        {
            jTextFieldshowgrade2.setText("C");
            gpa =gpa+2.0;
        }
        else if(subject2>=40&&subject2<50)
        {
            jTextFieldshowgrade2.setText("D");
            gpa =gpa+1.0;
        }
        else if(subject2<40)
        {
            jTextFieldshowgrade2.setText("F");
            gpa =gpa+0.0;
        }
        //subject3
        if (subject3>=80)
        {
            jTextFieldshowgrade3.setText("A");
            gpa =gpa+4.0;
        }
        else if(subject3>=65&&subject3<80)
        {
            jTextFieldshowgrade3.setText("B");
            gpa =gpa+3.0;
        }
        else if(subject3>=50&&subject3<65)
        {
            jTextFieldshowgrade3.setText("C");
            gpa =gpa+2.0;
        }
        else if(subject3>=40&&subject3<50)
        {
            jTextFieldshowgrade3.setText("D");
            gpa =gpa+1.0;
        }
        else if(subject3<40)
        {
            jTextFieldshowgrade3.setText("F");
            gpa =gpa+0.0;
        }
        //subject 4
        if (subject4>=80)
        {
            jTextFieldshowgrade4.setText("A");
            gpa =gpa+4.0;
        }
        else if(subject4>=65&&subject4<80)
        {
            jTextFieldshowgrade4.setText("B");
            gpa =gpa+3.0;
        }
        else if(subject4>=50&&subject4<65)
        {
            jTextFieldshowgrade4.setText("C");
            gpa =gpa+2.0;
        }
        else if(subject4>=40&&subject4<50)
        {
            jTextFieldshowgrade4.setText("D");
            gpa =gpa+1.0;
        }
        else if(subject4<40)
        {
            jTextFieldshowgrade4.setText("F");
            gpa =gpa+0.0;
        }
        //subject5
        if (subject5>=80)
        {
            jTextFieldshowgrade5.setText("A");
            gpa =gpa+4.0;
        }
        else if(subject5>=65&&subject5<80)
        {
            jTextFieldshowgrade5.setText("B");
            gpa =gpa+3.0;
        }
        else if(subject5>=50&&subject5<65)
        {
            jTextFieldshowgrade5.setText("C");
            gpa =gpa+2.0;
        }
        else if(subject5>=40&&subject5<50)
        {
            jTextFieldshowgrade5.setText("D");
            gpa =gpa+1.0;
        }
        else if(subject5<40)
        {
            jTextFieldshowgrade5.setText("F");
            gpa =gpa+0.0;
        }
        //subject 6
        if (subject6>=80)
        {
            jTextFieldshowgrade6.setText("A");
            gpa =gpa+4.0;
        }
        else if(subject6>=65&&subject6<80)
        {
            jTextFieldshowgrade6.setText("B");
            gpa =gpa+3.0;
        }
        else if(subject6>=50&&subject6<65)
        {
            jTextFieldshowgrade6.setText("C");
            gpa =gpa+2.0;
        }
        else if(subject6>=40&&subject6<50)
        {
            jTextFieldshowgrade6.setText("D");
            gpa =gpa+1.0;
        }
        else if(subject6<40)
        {
            jTextFieldshowgrade6.setText("F");
            gpa =gpa+0.0;
        }
        
        gpa=gpa/6.0;
        jTextFieldgpatotal.setText(String.format("%.2f",gpa));
        jTextFieldavggpa.setText(String.format("%.2f", average));
//        jTextFieldavggpa.setText(Double.toString("%.2f",average));
    }//GEN-LAST:event_jButtoncalculateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncalculate;
    private javax.swing.JLabel jLabelgpaavg;
    private javax.swing.JLabel jLabelgpatoal;
    private javax.swing.JLabel jLabelgradecal;
    private javax.swing.JLabel jLabelsubname1;
    private javax.swing.JLabel jLabelsubname2;
    private javax.swing.JLabel jLabelsubname3;
    private javax.swing.JLabel jLabelsubname4;
    private javax.swing.JLabel jLabelsubname5;
    private javax.swing.JLabel jLabelsubname6;
    private javax.swing.JLabel jLabelsubname7;
    private javax.swing.JLabel jLabelsubname8;
    private javax.swing.JLabel jLabelsubname9;
    private javax.swing.JPanel jPanelgpacal;
    private javax.swing.JTextField jTextFieldavggpa;
    private javax.swing.JTextField jTextFieldgpatotal;
    private javax.swing.JTextField jTextFieldgrade1;
    private javax.swing.JTextField jTextFieldgrade2;
    private javax.swing.JTextField jTextFieldgrade3;
    private javax.swing.JTextField jTextFieldgrade4;
    private javax.swing.JTextField jTextFieldgrade5;
    private javax.swing.JTextField jTextFieldgrade6;
    private javax.swing.JTextField jTextFieldshowgrade1;
    private javax.swing.JTextField jTextFieldshowgrade2;
    private javax.swing.JTextField jTextFieldshowgrade3;
    private javax.swing.JTextField jTextFieldshowgrade4;
    private javax.swing.JTextField jTextFieldshowgrade5;
    private javax.swing.JTextField jTextFieldshowgrade6;
    private javax.swing.JTextField jTextFieldsubnam1;
    private javax.swing.JTextField jTextFieldsubnam2;
    private javax.swing.JTextField jTextFieldsubnam3;
    private javax.swing.JTextField jTextFieldsubnam4;
    private javax.swing.JTextField jTextFieldsubnam5;
    private javax.swing.JTextField jTextFieldsubnam6;
    // End of variables declaration//GEN-END:variables
}
