/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.awt.Color;

/**
 *
 * @author one
 */
public class Home_Page extends javax.swing.JFrame {

    /**
     * Creates new form Home_Page
     */
    Color DefaultColor,ClickedColor;
    public Home_Page() {
        initComponents();
        this.setVisible(true);
        this.setTitle("Home Page");
        this.setResizable(false);
        DefaultColor = new Color(180,180,180);//set deafault color on run time
        ClickedColor =new Color(204,204,255);//set clicked color when clicked 
        
        jPanelstudinfo.setBackground(DefaultColor);
        jPanelstuden.setBackground(DefaultColor);
        jPanelstudatt.setBackground(DefaultColor);
        jPanelstudmidre.setBackground(DefaultColor);
        jPanelstudfinre.setBackground(DefaultColor);
        jPanelstudassg.setBackground(DefaultColor);
        jPanelstudgpacal.setBackground(DefaultColor);
        jPanelstudquiz.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelstudent = new javax.swing.JPanel();
        jPanelsidebarstud = new javax.swing.JPanel();
        jPanelstudinfo = new javax.swing.JPanel();
        jLabelstudinfo = new javax.swing.JLabel();
        jPanelstuden = new javax.swing.JPanel();
        jLabelstuden = new javax.swing.JLabel();
        jPanelstudatt = new javax.swing.JPanel();
        jLabelstudatt = new javax.swing.JLabel();
        jPanelstudfinre = new javax.swing.JPanel();
        jLabelfinre = new javax.swing.JLabel();
        jPanelstudmidre = new javax.swing.JPanel();
        jLabelstudmidre = new javax.swing.JLabel();
        jPanelstudassg = new javax.swing.JPanel();
        jLabelstudassg = new javax.swing.JLabel();
        jPanelstudgpacal = new javax.swing.JPanel();
        jLabelstudgpacal = new javax.swing.JLabel();
        jPanelstudquiz = new javax.swing.JPanel();
        jLabelstudquiz = new javax.swing.JLabel();
        jLabelstupor = new javax.swing.JLabel();
        jDesktopPanestud = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelstudent.setBackground(new java.awt.Color(204, 204, 255));
        jPanelstudent.setMinimumSize(new java.awt.Dimension(1000, 625));
        jPanelstudent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelsidebarstud.setBackground(new java.awt.Color(180, 180, 180));
        jPanelsidebarstud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelstudinfo.setBackground(new java.awt.Color(180, 180, 180));

        jLabelstudinfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstudinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/img/icons8-identification-documents-50.png"))); // NOI18N
        jLabelstudinfo.setText("  Student Iformation");
        jLabelstudinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelstudinfoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelstudinfoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelstudinfoLayout = new javax.swing.GroupLayout(jPanelstudinfo);
        jPanelstudinfo.setLayout(jPanelstudinfoLayout);
        jPanelstudinfoLayout.setHorizontalGroup(
            jPanelstudinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelstudinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelstudinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelstudinfoLayout.setVerticalGroup(
            jPanelstudinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelstudinfo, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        jPanelsidebarstud.add(jPanelstudinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 141, -1, -1));

        jPanelstuden.setBackground(new java.awt.Color(180, 180, 180));

        jLabelstuden.setBackground(new java.awt.Color(180, 180, 180));
        jLabelstuden.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstuden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/img/icons8-enrollment-64 (1).png"))); // NOI18N
        jLabelstuden.setText("  Enrollement");
        jLabelstuden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelstudenMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelstudenLayout = new javax.swing.GroupLayout(jPanelstuden);
        jPanelstuden.setLayout(jPanelstudenLayout);
        jPanelstudenLayout.setHorizontalGroup(
            jPanelstudenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelstudenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelstuden, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelstudenLayout.setVerticalGroup(
            jPanelstudenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelstuden, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelsidebarstud.add(jPanelstuden, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 60));

        jPanelstudatt.setBackground(new java.awt.Color(180, 180, 180));

        jLabelstudatt.setBackground(new java.awt.Color(180, 180, 180));
        jLabelstudatt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstudatt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/img/icons8-attendance-48.png"))); // NOI18N
        jLabelstudatt.setText("    Attendence");
        jLabelstudatt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelstudattMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelstudattLayout = new javax.swing.GroupLayout(jPanelstudatt);
        jPanelstudatt.setLayout(jPanelstudattLayout);
        jPanelstudattLayout.setHorizontalGroup(
            jPanelstudattLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelstudatt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanelstudattLayout.setVerticalGroup(
            jPanelstudattLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelstudatt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelsidebarstud.add(jPanelstudatt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 240, 60));

        jPanelstudfinre.setBackground(new java.awt.Color(180, 180, 180));

        jLabelfinre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelfinre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/img/icons8-test-results-50.png"))); // NOI18N
        jLabelfinre.setText("   Final Result");
        jLabelfinre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelfinreMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelstudfinreLayout = new javax.swing.GroupLayout(jPanelstudfinre);
        jPanelstudfinre.setLayout(jPanelstudfinreLayout);
        jPanelstudfinreLayout.setHorizontalGroup(
            jPanelstudfinreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelfinre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanelstudfinreLayout.setVerticalGroup(
            jPanelstudfinreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelfinre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelsidebarstud.add(jPanelstudfinre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 240, 60));

        jPanelstudmidre.setBackground(new java.awt.Color(180, 180, 180));

        jLabelstudmidre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstudmidre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/img/icons8-test-results-50.png"))); // NOI18N
        jLabelstudmidre.setText("    Mid Result");
        jLabelstudmidre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelstudmidreMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelstudmidreLayout = new javax.swing.GroupLayout(jPanelstudmidre);
        jPanelstudmidre.setLayout(jPanelstudmidreLayout);
        jPanelstudmidreLayout.setHorizontalGroup(
            jPanelstudmidreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelstudmidreLayout.createSequentialGroup()
                .addComponent(jLabelstudmidre, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelstudmidreLayout.setVerticalGroup(
            jPanelstudmidreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelstudmidre, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelsidebarstud.add(jPanelstudmidre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 60));

        jPanelstudassg.setBackground(new java.awt.Color(180, 180, 180));

        jLabelstudassg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstudassg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/img/icons8-test-results-50.png"))); // NOI18N
        jLabelstudassg.setText("Assignment Grades");
        jLabelstudassg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelstudassgMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelstudassgLayout = new javax.swing.GroupLayout(jPanelstudassg);
        jPanelstudassg.setLayout(jPanelstudassgLayout);
        jPanelstudassgLayout.setHorizontalGroup(
            jPanelstudassgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelstudassg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanelstudassgLayout.setVerticalGroup(
            jPanelstudassgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelstudassg, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelsidebarstud.add(jPanelstudassg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 240, 60));

        jPanelstudgpacal.setBackground(new java.awt.Color(180, 180, 180));

        jLabelstudgpacal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstudgpacal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/img/icons8-gpa-calculator-50.png"))); // NOI18N
        jLabelstudgpacal.setText("GPA Calculator");
        jLabelstudgpacal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelstudgpacalMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelstudgpacalLayout = new javax.swing.GroupLayout(jPanelstudgpacal);
        jPanelstudgpacal.setLayout(jPanelstudgpacalLayout);
        jPanelstudgpacalLayout.setHorizontalGroup(
            jPanelstudgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelstudgpacal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanelstudgpacalLayout.setVerticalGroup(
            jPanelstudgpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelstudgpacal, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelsidebarstud.add(jPanelstudgpacal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 240, 60));

        jPanelstudquiz.setBackground(new java.awt.Color(180, 180, 180));

        jLabelstudquiz.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstudquiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/img/icons8-quiz-50.png"))); // NOI18N
        jLabelstudquiz.setText(" Quiz Numbers");
        jLabelstudquiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelstudquizMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelstudquizLayout = new javax.swing.GroupLayout(jPanelstudquiz);
        jPanelstudquiz.setLayout(jPanelstudquizLayout);
        jPanelstudquizLayout.setHorizontalGroup(
            jPanelstudquizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelstudquiz, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanelstudquizLayout.setVerticalGroup(
            jPanelstudquizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelstudquiz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelsidebarstud.add(jPanelstudquiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 240, 60));

        jPanelstudent.add(jPanelsidebarstud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 720));

        jLabelstupor.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelstupor.setForeground(new java.awt.Color(0, 102, 204));
        jLabelstupor.setText("Student Portal");
        jPanelstudent.add(jLabelstupor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 270, 60));

        jDesktopPanestud.setBackground(new java.awt.Color(255, 255, 255));
        jPanelstudent.add(jDesktopPanestud, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 1110, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelstudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelstudent, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelstudinfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelstudinfoMousePressed
        // TODO add your handling code here:
        jPanelstudinfo.setBackground(ClickedColor);
        jPanelstuden.setBackground(DefaultColor);
        jPanelstudatt.setBackground(DefaultColor);
        jPanelstudmidre.setBackground(DefaultColor);
        jPanelstudfinre.setBackground(DefaultColor);
        jPanelstudassg.setBackground(DefaultColor);
        jPanelstudgpacal.setBackground(DefaultColor);
        jPanelstudquiz.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabelstudinfoMousePressed

    private void jLabelstudenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelstudenMousePressed
        // TODO add your handling code here:
        jPanelstudinfo.setBackground(DefaultColor);
        jPanelstuden.setBackground(ClickedColor);
        jPanelstudatt.setBackground(DefaultColor);
        jPanelstudmidre.setBackground(DefaultColor);
        jPanelstudfinre.setBackground(DefaultColor);
        jPanelstudassg.setBackground(DefaultColor);
        jPanelstudgpacal.setBackground(DefaultColor);
        jPanelstudquiz.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabelstudenMousePressed

    private void jLabelstudattMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelstudattMousePressed
        // TODO add your handling code here:
        jPanelstudinfo.setBackground(DefaultColor);
        jPanelstuden.setBackground(DefaultColor);
        jPanelstudatt.setBackground(ClickedColor);
        jPanelstudmidre.setBackground(DefaultColor);
        jPanelstudfinre.setBackground(DefaultColor);
        jPanelstudassg.setBackground(DefaultColor);
        jPanelstudgpacal.setBackground(DefaultColor);
        jPanelstudquiz.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabelstudattMousePressed

    private void jLabelstudmidreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelstudmidreMousePressed
        // TODO add your handling code here:
        jPanelstudinfo.setBackground(DefaultColor);
        jPanelstuden.setBackground(DefaultColor);
        jPanelstudatt.setBackground(DefaultColor);
        jPanelstudmidre.setBackground(ClickedColor);
        jPanelstudfinre.setBackground(DefaultColor);
        jPanelstudassg.setBackground(DefaultColor);
        jPanelstudgpacal.setBackground(DefaultColor);
        jPanelstudquiz.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabelstudmidreMousePressed

    private void jLabelfinreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelfinreMousePressed
        // TODO add your handling code here:
        jPanelstudinfo.setBackground(DefaultColor);
        jPanelstuden.setBackground(DefaultColor);
        jPanelstudatt.setBackground(DefaultColor);
        jPanelstudmidre.setBackground(DefaultColor);
        jPanelstudfinre.setBackground(ClickedColor);
        jPanelstudassg.setBackground(DefaultColor);
        jPanelstudgpacal.setBackground(DefaultColor);
        jPanelstudquiz.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabelfinreMousePressed

    private void jLabelstudassgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelstudassgMousePressed
        // TODO add your handling code here:
        jPanelstudinfo.setBackground(DefaultColor);
        jPanelstuden.setBackground(DefaultColor);
        jPanelstudatt.setBackground(DefaultColor);
        jPanelstudmidre.setBackground(DefaultColor);
        jPanelstudfinre.setBackground(DefaultColor);
        jPanelstudassg.setBackground(ClickedColor);
        jPanelstudgpacal.setBackground(DefaultColor);
        jPanelstudquiz.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabelstudassgMousePressed

    private void jLabelstudgpacalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelstudgpacalMousePressed
        // TODO add your handling code here:
        jPanelstudinfo.setBackground(DefaultColor);
        jPanelstuden.setBackground(DefaultColor);
        jPanelstudatt.setBackground(DefaultColor);
        jPanelstudmidre.setBackground(DefaultColor);
        jPanelstudfinre.setBackground(DefaultColor);
        jPanelstudassg.setBackground(DefaultColor);
        jPanelstudgpacal.setBackground(ClickedColor);
        jPanelstudquiz.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabelstudgpacalMousePressed

    private void jLabelstudquizMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelstudquizMousePressed
        // TODO add your handling code here:
        jPanelstudinfo.setBackground(DefaultColor);
        jPanelstuden.setBackground(DefaultColor);
        jPanelstudatt.setBackground(DefaultColor);
        jPanelstudmidre.setBackground(DefaultColor);
        jPanelstudfinre.setBackground(DefaultColor);
        jPanelstudassg.setBackground(DefaultColor);
        jPanelstudgpacal.setBackground(DefaultColor);
        jPanelstudquiz.setBackground(ClickedColor);
    }//GEN-LAST:event_jLabelstudquizMousePressed

    private void jLabelstudinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelstudinfoMouseClicked
        // TODO add your handling code here:
//        Student_Info student=new  Student_Info();
//        jDesktopPanestud.removeAll();
//        jDesktopPanestud.add(student).setVisible(true);
    }//GEN-LAST:event_jLabelstudinfoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Page().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanestud;
    private javax.swing.JLabel jLabelfinre;
    private javax.swing.JLabel jLabelstudassg;
    private javax.swing.JLabel jLabelstudatt;
    private javax.swing.JLabel jLabelstuden;
    private javax.swing.JLabel jLabelstudgpacal;
    private javax.swing.JLabel jLabelstudinfo;
    private javax.swing.JLabel jLabelstudmidre;
    private javax.swing.JLabel jLabelstudquiz;
    private javax.swing.JLabel jLabelstupor;
    private javax.swing.JPanel jPanelsidebarstud;
    private javax.swing.JPanel jPanelstudassg;
    private javax.swing.JPanel jPanelstudatt;
    private javax.swing.JPanel jPanelstuden;
    private javax.swing.JPanel jPanelstudent;
    private javax.swing.JPanel jPanelstudfinre;
    private javax.swing.JPanel jPanelstudgpacal;
    private javax.swing.JPanel jPanelstudinfo;
    private javax.swing.JPanel jPanelstudmidre;
    private javax.swing.JPanel jPanelstudquiz;
    // End of variables declaration//GEN-END:variables
}
