/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.awt.Color;

/**
 *
 * @author one
 */

public class Home_Page_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Home_Page_Admin
     */
    Color DefaultColor,ClickedColor;
    public Home_Page_Admin() {
        initComponents();
        this.setVisible(true);
        this.setTitle("Home Page");
        this.setResizable(false);
        DefaultColor = new Color(180,180,180);//set deafault color on run time
        ClickedColor =new Color(204,204,255);//set clicked color when clicked 
        
       jPaneladminstudent.setBackground(DefaultColor);
        jPaneladminprofessor.setBackground(DefaultColor);
        jPaneladminstudentattendance.setBackground(DefaultColor);
        jPaneladminstudentmidresult.setBackground(DefaultColor);
        jPaneladminstudentfinalresult.setBackground(DefaultColor);
       
        jPaneladmingpacal.setBackground(DefaultColor);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneladmin = new javax.swing.JPanel();
        jPanelsidebaradmin = new javax.swing.JPanel();
        jPaneladminstudent = new javax.swing.JPanel();
        jLabeladminstudent = new javax.swing.JLabel();
        jPaneladminprofessor = new javax.swing.JPanel();
        jLabeladminprofesor = new javax.swing.JLabel();
        jPaneladminstudentattendance = new javax.swing.JPanel();
        jLabeladminstudentattendence = new javax.swing.JLabel();
        jPaneladminstudentfinalresult = new javax.swing.JPanel();
        jLabeladminfinalresult = new javax.swing.JLabel();
        jPaneladminstudentmidresult = new javax.swing.JPanel();
        jLabeladminstudentmidresult = new javax.swing.JLabel();
        jPaneladmingpacal = new javax.swing.JPanel();
        jLabeladmingpacal = new javax.swing.JLabel();
        jLabeladmpor = new javax.swing.JLabel();
        jDesktopPaneadm = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPaneladmin.setBackground(new java.awt.Color(204, 204, 255));
        jPaneladmin.setMinimumSize(new java.awt.Dimension(1000, 625));
        jPaneladmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelsidebaradmin.setBackground(new java.awt.Color(180, 180, 180));
        jPanelsidebaradmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPaneladminstudent.setBackground(new java.awt.Color(180, 180, 180));

        jLabeladminstudent.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabeladminstudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/img/icons8-identification-documents-50.png"))); // NOI18N
        jLabeladminstudent.setText("  Student ");
        jLabeladminstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeladminstudentMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabeladminstudentMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPaneladminstudentLayout = new javax.swing.GroupLayout(jPaneladminstudent);
        jPaneladminstudent.setLayout(jPaneladminstudentLayout);
        jPaneladminstudentLayout.setHorizontalGroup(
            jPaneladminstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneladminstudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeladminstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaneladminstudentLayout.setVerticalGroup(
            jPaneladminstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabeladminstudent, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        jPanelsidebaradmin.add(jPaneladminstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 141, -1, -1));

        jPaneladminprofessor.setBackground(new java.awt.Color(180, 180, 180));

        jLabeladminprofesor.setBackground(new java.awt.Color(180, 180, 180));
        jLabeladminprofesor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabeladminprofesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/img/icons8-teacher-50.png"))); // NOI18N
        jLabeladminprofesor.setText("   Professors");
        jLabeladminprofesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeladminprofesorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabeladminprofesorMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPaneladminprofessorLayout = new javax.swing.GroupLayout(jPaneladminprofessor);
        jPaneladminprofessor.setLayout(jPaneladminprofessorLayout);
        jPaneladminprofessorLayout.setHorizontalGroup(
            jPaneladminprofessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneladminprofessorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeladminprofesor, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
        );
        jPaneladminprofessorLayout.setVerticalGroup(
            jPaneladminprofessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabeladminprofesor, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelsidebaradmin.add(jPaneladminprofessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 60));

        jPaneladminstudentattendance.setBackground(new java.awt.Color(180, 180, 180));

        jLabeladminstudentattendence.setBackground(new java.awt.Color(180, 180, 180));
        jLabeladminstudentattendence.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabeladminstudentattendence.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/img/icons8-attendance-48.png"))); // NOI18N
        jLabeladminstudentattendence.setText("    Attendence");
        jLabeladminstudentattendence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabeladminstudentattendenceMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPaneladminstudentattendanceLayout = new javax.swing.GroupLayout(jPaneladminstudentattendance);
        jPaneladminstudentattendance.setLayout(jPaneladminstudentattendanceLayout);
        jPaneladminstudentattendanceLayout.setHorizontalGroup(
            jPaneladminstudentattendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabeladminstudentattendence, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPaneladminstudentattendanceLayout.setVerticalGroup(
            jPaneladminstudentattendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabeladminstudentattendence, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelsidebaradmin.add(jPaneladminstudentattendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 240, 60));

        jPaneladminstudentfinalresult.setBackground(new java.awt.Color(180, 180, 180));

        jLabeladminfinalresult.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabeladminfinalresult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/img/icons8-test-results-50.png"))); // NOI18N
        jLabeladminfinalresult.setText("   Final Result");
        jLabeladminfinalresult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabeladminfinalresultMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeladminfinalresultMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPaneladminstudentfinalresultLayout = new javax.swing.GroupLayout(jPaneladminstudentfinalresult);
        jPaneladminstudentfinalresult.setLayout(jPaneladminstudentfinalresultLayout);
        jPaneladminstudentfinalresultLayout.setHorizontalGroup(
            jPaneladminstudentfinalresultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabeladminfinalresult, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPaneladminstudentfinalresultLayout.setVerticalGroup(
            jPaneladminstudentfinalresultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneladminstudentfinalresultLayout.createSequentialGroup()
                .addComponent(jLabeladminfinalresult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        jPanelsidebaradmin.add(jPaneladminstudentfinalresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 240, 50));

        jPaneladminstudentmidresult.setBackground(new java.awt.Color(180, 180, 180));

        jLabeladminstudentmidresult.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabeladminstudentmidresult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/img/icons8-test-results-50.png"))); // NOI18N
        jLabeladminstudentmidresult.setText("    Mid Result");
        jLabeladminstudentmidresult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeladminstudentmidresultMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabeladminstudentmidresultMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPaneladminstudentmidresultLayout = new javax.swing.GroupLayout(jPaneladminstudentmidresult);
        jPaneladminstudentmidresult.setLayout(jPaneladminstudentmidresultLayout);
        jPaneladminstudentmidresultLayout.setHorizontalGroup(
            jPaneladminstudentmidresultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneladminstudentmidresultLayout.createSequentialGroup()
                .addComponent(jLabeladminstudentmidresult, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPaneladminstudentmidresultLayout.setVerticalGroup(
            jPaneladminstudentmidresultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabeladminstudentmidresult, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelsidebaradmin.add(jPaneladminstudentmidresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 60));

        jPaneladmingpacal.setBackground(new java.awt.Color(180, 180, 180));

        jLabeladmingpacal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabeladmingpacal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/img/icons8-gpa-calculator-50.png"))); // NOI18N
        jLabeladmingpacal.setText("GPA Calculator");
        jLabeladmingpacal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabeladmingpacalMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabeladmingpacalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPaneladmingpacalLayout = new javax.swing.GroupLayout(jPaneladmingpacal);
        jPaneladmingpacal.setLayout(jPaneladmingpacalLayout);
        jPaneladmingpacalLayout.setHorizontalGroup(
            jPaneladmingpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneladmingpacalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabeladmingpacal, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPaneladmingpacalLayout.setVerticalGroup(
            jPaneladmingpacalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneladmingpacalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabeladmingpacal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelsidebaradmin.add(jPaneladmingpacal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 240, 60));

        jPaneladmin.add(jPanelsidebaradmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 720));

        jLabeladmpor.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabeladmpor.setForeground(new java.awt.Color(0, 102, 204));
        jLabeladmpor.setText("Admin Portal");
        jPaneladmin.add(jLabeladmpor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 270, 60));

        jDesktopPaneadm.setBackground(new java.awt.Color(255, 255, 255));
        jPaneladmin.add(jDesktopPaneadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 1110, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPaneladmin, javax.swing.GroupLayout.PREFERRED_SIZE, 1355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPaneladmin, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabeladminstudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeladminstudentMouseClicked
        // TODO add your handling code here:
        Manage_Student managestudent=new  Manage_Student();
        jDesktopPaneadm.removeAll();
        jDesktopPaneadm.add(managestudent).setVisible(true);
    }//GEN-LAST:event_jLabeladminstudentMouseClicked

    private void jLabeladminstudentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeladminstudentMousePressed
        // TODO add your handling code here:
        jPaneladminstudent.setBackground(ClickedColor);
        jPaneladminprofessor.setBackground(DefaultColor);
        jPaneladminstudentattendance.setBackground(DefaultColor);
        jPaneladminstudentmidresult.setBackground(DefaultColor);
        jPaneladminstudentfinalresult.setBackground(DefaultColor);
        
        jPaneladmingpacal.setBackground(DefaultColor);
       
    }//GEN-LAST:event_jLabeladminstudentMousePressed

    private void jLabeladminprofesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeladminprofesorMousePressed
        // TODO add your handling code here:
        jPaneladminstudent.setBackground(DefaultColor);
        jPaneladminprofessor.setBackground(ClickedColor);
        jPaneladminstudentattendance.setBackground(DefaultColor);
        jPaneladminstudentmidresult.setBackground(DefaultColor);
        jPaneladminstudentfinalresult.setBackground(DefaultColor);
        
        jPaneladmingpacal.setBackground(DefaultColor);
        
    }//GEN-LAST:event_jLabeladminprofesorMousePressed

    private void jLabeladminstudentattendenceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeladminstudentattendenceMousePressed
        // TODO add your handling code here:
        jPaneladminstudent.setBackground(DefaultColor);
        jPaneladminprofessor.setBackground(DefaultColor);
        jPaneladminstudentattendance.setBackground(ClickedColor);
        jPaneladminstudentmidresult.setBackground(DefaultColor);
        jPaneladminstudentfinalresult.setBackground(DefaultColor);
       
        jPaneladmingpacal.setBackground(DefaultColor);
        
    }//GEN-LAST:event_jLabeladminstudentattendenceMousePressed

    private void jLabeladminfinalresultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeladminfinalresultMousePressed
        // TODO add your handling code here:
        jPaneladminstudent.setBackground(DefaultColor);
        jPaneladminprofessor.setBackground(DefaultColor);
        jPaneladminstudentattendance.setBackground(DefaultColor);
        jPaneladminstudentmidresult.setBackground(DefaultColor);
        jPaneladminstudentfinalresult.setBackground(ClickedColor);
       
        jPaneladmingpacal.setBackground(DefaultColor);
        
    }//GEN-LAST:event_jLabeladminfinalresultMousePressed

    private void jLabeladminstudentmidresultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeladminstudentmidresultMousePressed
        // TODO add your handling code here:
        jPaneladminstudent.setBackground(DefaultColor);
        jPaneladminprofessor.setBackground(DefaultColor);
        jPaneladminstudentattendance.setBackground(DefaultColor);
        jPaneladminstudentmidresult.setBackground(ClickedColor);
        jPaneladminstudentfinalresult.setBackground(DefaultColor);
       
        jPaneladmingpacal.setBackground(DefaultColor);
       
    }//GEN-LAST:event_jLabeladminstudentmidresultMousePressed

    private void jLabeladmingpacalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeladmingpacalMouseClicked
        // TODO add your handling code here:
        Gpa_calculator gpa=new  Gpa_calculator();
        jDesktopPaneadm.removeAll();
        jDesktopPaneadm.add(gpa).setVisible(true);
    }//GEN-LAST:event_jLabeladmingpacalMouseClicked

    private void jLabeladmingpacalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeladmingpacalMousePressed
        // TODO add your handling code here:
        jPaneladminstudent.setBackground(DefaultColor);
        jPaneladminprofessor.setBackground(DefaultColor);
        jPaneladminstudentattendance.setBackground(DefaultColor);
        jPaneladminstudentmidresult.setBackground(DefaultColor);
        jPaneladminstudentfinalresult.setBackground(DefaultColor);
        jPaneladmingpacal.setBackground(ClickedColor);
        
    }//GEN-LAST:event_jLabeladmingpacalMousePressed

    private void jLabeladminprofesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeladminprofesorMouseClicked
        // TODO add your handling code here:
       Manage_Teacher managestudent=new  Manage_Teacher();
        jDesktopPaneadm.removeAll();
        jDesktopPaneadm.add(managestudent).setVisible(true);
    }//GEN-LAST:event_jLabeladminprofesorMouseClicked

    private void jLabeladminstudentmidresultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeladminstudentmidresultMouseClicked
        // TODO add your handling code here:
        Mid_Result midresult=new  Mid_Result();
        jDesktopPaneadm.removeAll();
        jDesktopPaneadm.add(midresult).setVisible(true);
    }//GEN-LAST:event_jLabeladminstudentmidresultMouseClicked

    private void jLabeladminfinalresultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabeladminfinalresultMouseClicked
        // TODO add your handling code here:
         Final_Result finresult=new  Final_Result();
        jDesktopPaneadm.removeAll();
        jDesktopPaneadm.add(finresult).setVisible(true);
        
    }//GEN-LAST:event_jLabeladminfinalresultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Page_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Page_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Page_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Page_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Page_Admin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneadm;
    private javax.swing.JLabel jLabeladminfinalresult;
    private javax.swing.JLabel jLabeladmingpacal;
    private javax.swing.JLabel jLabeladminprofesor;
    private javax.swing.JLabel jLabeladminstudent;
    private javax.swing.JLabel jLabeladminstudentattendence;
    private javax.swing.JLabel jLabeladminstudentmidresult;
    private javax.swing.JLabel jLabeladmpor;
    private javax.swing.JPanel jPaneladmin;
    private javax.swing.JPanel jPaneladmingpacal;
    private javax.swing.JPanel jPaneladminprofessor;
    private javax.swing.JPanel jPaneladminstudent;
    private javax.swing.JPanel jPaneladminstudentattendance;
    private javax.swing.JPanel jPaneladminstudentfinalresult;
    private javax.swing.JPanel jPaneladminstudentmidresult;
    private javax.swing.JPanel jPanelsidebaradmin;
    // End of variables declaration//GEN-END:variables
}
