/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author one
 */
public class Manage_Student extends javax.swing.JInternalFrame {
   

    /**
     * Creates new form Manage_Student
     */
    public Manage_Student() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanelmanagestudents = new javax.swing.JPanel();
        jLabelstudfirstname = new javax.swing.JLabel();
        jTextFieldstudfirstname = new javax.swing.JTextField();
        jLabelstudsecondname = new javax.swing.JLabel();
        jTextFieldstudsecondname1 = new javax.swing.JTextField();
        jLabelstudDOB = new javax.swing.JLabel();
        jDatestuddob = new com.toedter.calendar.JDateChooser();
        jLabelstudgender = new javax.swing.JLabel();
        jLabelstudcontantno = new javax.swing.JLabel();
        jTextFieldstudcontantno = new javax.swing.JTextField();
        jLabelstudemail = new javax.swing.JLabel();
        jTextFieldstudemail = new javax.swing.JTextField();
        jLabelstudfathername = new javax.swing.JLabel();
        jTextFieldstudfathername = new javax.swing.JTextField();
        jLabelstudfatheroccupation = new javax.swing.JLabel();
        jTextFieldstudfatheroccupation = new javax.swing.JTextField();
        jLabelstudaddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreastudaddress = new javax.swing.JTextArea();
        jRadioButtonmale = new javax.swing.JRadioButton();
        jRadioButtonfemale = new javax.swing.JRadioButton();
        jPanelacademicinfo = new javax.swing.JPanel();
        jLabelstudclassname = new javax.swing.JLabel();
        jLabelstuddateofaddmissions = new javax.swing.JLabel();
        jLabelstuddepartment = new javax.swing.JLabel();
        jLabelstudid = new javax.swing.JLabel();
        jTextFieldstudid = new javax.swing.JTextField();
        jDateChooserdateofaddmission = new com.toedter.calendar.JDateChooser();
        jRadioButtonse = new javax.swing.JRadioButton();
        jRadioButtoncs = new javax.swing.JRadioButton();
        jRadioButtonit = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanelstudbuttons = new javax.swing.JPanel();
        jButtonstudadd = new javax.swing.JButton();
        jButtonstudrecord = new javax.swing.JButton();

        jPanelmanagestudents.setBackground(new java.awt.Color(153, 153, 153));
        jPanelmanagestudents.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Basic Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 36))); // NOI18N

        jLabelstudfirstname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstudfirstname.setText("First Name :");

        jTextFieldstudfirstname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldstudfirstname.setText(" ");

        jLabelstudsecondname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstudsecondname.setText("Second Name :");

        jTextFieldstudsecondname1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldstudsecondname1.setText(" ");

        jLabelstudDOB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstudDOB.setText("Date of Birth :");

        jDatestuddob.setDateFormatString("yyyy-MM-dd");

        jLabelstudgender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstudgender.setText("Gender:");

        jLabelstudcontantno.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstudcontantno.setText("Contant No :");

        jTextFieldstudcontantno.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldstudcontantno.setText(" ");

        jLabelstudemail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstudemail.setText("Email :");

        jTextFieldstudemail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldstudemail.setText(" ");

        jLabelstudfathername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstudfathername.setText("Father Name :");

        jTextFieldstudfathername.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldstudfathername.setText(" ");

        jLabelstudfatheroccupation.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstudfatheroccupation.setText("Occupation :");

        jTextFieldstudfatheroccupation.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldstudfatheroccupation.setText(" ");
        jTextFieldstudfatheroccupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldstudfatheroccupationActionPerformed(evt);
            }
        });

        jLabelstudaddress.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstudaddress.setText("Address :");

        jTextAreastudaddress.setColumns(20);
        jTextAreastudaddress.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextAreastudaddress.setRows(5);
        jScrollPane1.setViewportView(jTextAreastudaddress);

        buttonGroup2.add(jRadioButtonmale);
        jRadioButtonmale.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButtonmale.setText("Male");
        jRadioButtonmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonmaleActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonfemale);
        jRadioButtonfemale.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButtonfemale.setText("Female");
        jRadioButtonfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonfemaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelmanagestudentsLayout = new javax.swing.GroupLayout(jPanelmanagestudents);
        jPanelmanagestudents.setLayout(jPanelmanagestudentsLayout);
        jPanelmanagestudentsLayout.setHorizontalGroup(
            jPanelmanagestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmanagestudentsLayout.createSequentialGroup()
                .addGroup(jPanelmanagestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelmanagestudentsLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanelmanagestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelstudfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelstudgender, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelmanagestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelmanagestudentsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldstudfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelmanagestudentsLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jRadioButtonmale)
                                .addGap(27, 27, 27)
                                .addComponent(jRadioButtonfemale))))
                    .addGroup(jPanelmanagestudentsLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelstudfathername, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldstudfathername, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jPanelmanagestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelmanagestudentsLayout.createSequentialGroup()
                        .addComponent(jLabelstudsecondname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldstudsecondname1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelmanagestudentsLayout.createSequentialGroup()
                        .addComponent(jLabelstudcontantno, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldstudcontantno, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelmanagestudentsLayout.createSequentialGroup()
                        .addComponent(jLabelstudfatheroccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldstudfatheroccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanelmanagestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelmanagestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelmanagestudentsLayout.createSequentialGroup()
                            .addComponent(jLabelstudaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelmanagestudentsLayout.createSequentialGroup()
                            .addComponent(jLabelstudemail, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldstudemail, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelmanagestudentsLayout.createSequentialGroup()
                        .addComponent(jLabelstudDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDatestuddob, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanelmanagestudentsLayout.setVerticalGroup(
            jPanelmanagestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmanagestudentsLayout.createSequentialGroup()
                .addGroup(jPanelmanagestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelmanagestudentsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDatestuddob, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelmanagestudentsLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanelmanagestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelstudfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldstudfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelstudsecondname, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldstudsecondname1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelstudDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanelmanagestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelmanagestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelstudgender, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelstudcontantno, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButtonmale)
                        .addComponent(jRadioButtonfemale))
                    .addGroup(jPanelmanagestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldstudcontantno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelstudemail, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldstudemail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelmanagestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelmanagestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelmanagestudentsLayout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(jPanelmanagestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldstudfathername, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelstudfathername, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelmanagestudentsLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(jPanelmanagestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelstudfatheroccupation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldstudfatheroccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelstudaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelmanagestudentsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelacademicinfo.setBackground(new java.awt.Color(153, 153, 153));
        jPanelacademicinfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Academic Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N

        jLabelstudclassname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstudclassname.setText("Class Name :");

        jLabelstuddateofaddmissions.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstuddateofaddmissions.setText("Date Of Addmissions :");

        jLabelstuddepartment.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstuddepartment.setText("Department :");

        jLabelstudid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelstudid.setText("Student ID:");

        jTextFieldstudid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldstudid.setText(" ");
        jTextFieldstudid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldstudidActionPerformed(evt);
            }
        });

        jDateChooserdateofaddmission.setDateFormatString("yyyy-MM-dd");

        buttonGroup1.add(jRadioButtonse);
        jRadioButtonse.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButtonse.setText("SE");
        jRadioButtonse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonseActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtoncs);
        jRadioButtoncs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButtoncs.setText("CS");

        buttonGroup1.add(jRadioButtonit);
        jRadioButtonit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButtonit.setText("IT");

        buttonGroup3.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton1.setText("A");

        buttonGroup3.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton2.setText("B");

        buttonGroup3.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton3.setText("C");

        buttonGroup3.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton4.setText("D");

        javax.swing.GroupLayout jPanelacademicinfoLayout = new javax.swing.GroupLayout(jPanelacademicinfo);
        jPanelacademicinfo.setLayout(jPanelacademicinfoLayout);
        jPanelacademicinfoLayout.setHorizontalGroup(
            jPanelacademicinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelacademicinfoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelacademicinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelstudclassname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelstudid, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelacademicinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldstudid, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelacademicinfoLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(10, 10, 10)
                        .addComponent(jRadioButton2)
                        .addGap(10, 10, 10)
                        .addComponent(jRadioButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton4)))
                .addGap(28, 28, 28)
                .addGroup(jPanelacademicinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelstuddateofaddmissions)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelacademicinfoLayout.createSequentialGroup()
                        .addComponent(jLabelstuddepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGap(56, 56, 56)
                .addGroup(jPanelacademicinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserdateofaddmission, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelacademicinfoLayout.createSequentialGroup()
                        .addComponent(jRadioButtonse)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtoncs)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelacademicinfoLayout.setVerticalGroup(
            jPanelacademicinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelacademicinfoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelacademicinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelstudid, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldstudid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelstuddateofaddmissions, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserdateofaddmission, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelacademicinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelacademicinfoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelacademicinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelstudclassname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelacademicinfoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelacademicinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelacademicinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButtonse)
                                .addComponent(jRadioButtoncs)
                                .addComponent(jRadioButtonit))
                            .addComponent(jLabelstuddepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanelstudbuttons.setBackground(new java.awt.Color(153, 153, 153));

        jButtonstudadd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonstudadd.setText("Add New");
        jButtonstudadd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonstudadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonstudaddActionPerformed(evt);
            }
        });

        jButtonstudrecord.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonstudrecord.setText("Students Records");
        jButtonstudrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonstudrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonstudrecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelstudbuttonsLayout = new javax.swing.GroupLayout(jPanelstudbuttons);
        jPanelstudbuttons.setLayout(jPanelstudbuttonsLayout);
        jPanelstudbuttonsLayout.setHorizontalGroup(
            jPanelstudbuttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelstudbuttonsLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButtonstudadd, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonstudrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanelstudbuttonsLayout.setVerticalGroup(
            jPanelstudbuttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelstudbuttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelstudbuttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonstudadd, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButtonstudrecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelmanagestudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelstudbuttons, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelacademicinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelmanagestudents, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelacademicinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelstudbuttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldstudidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldstudidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldstudidActionPerformed

    private void jTextFieldstudfatheroccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldstudfatheroccupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldstudfatheroccupationActionPerformed

    private void jButtonstudaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonstudaddActionPerformed
        // TODO add your handling code here:
        try{
            
                Class.forName("com.mysql.jdbc.Driver");  
            
             Connection conn=DriverManager.getConnection
                     ("jdbc:mysql://localhost:3306/admin_login","root","");
             PreparedStatement pstmt = conn.prepareStatement
                     ("INSERT INTO student (firstname, secondname, dob, gender, number, email,fathername, occupation, address, studentid, doa,section, classname) values (?,?,?,?,?,?,?,?,?,?,?,?,?) ");
                          pstmt.setString(1, jTextFieldstudfirstname.getText());
                          pstmt.setString(2, jTextFieldstudsecondname1.getText());
                          pstmt.setString(3, ((JTextField)jDatestuddob.getDateEditor().getUiComponent()).getText());
                          String gender="";
                          if(jRadioButtonmale.isSelected())
                          {
                              gender =jRadioButtonmale.getText();
                          }
                          if(jRadioButtonfemale.isSelected())
                          {
                              gender =jRadioButtonfemale.getText();
                          }
                          pstmt.setString(4, gender);
                          pstmt.setString(5, jTextFieldstudcontantno.getText());
                          pstmt.setString(6, jTextFieldstudemail.getText());
                          pstmt.setString(7, jTextFieldstudfathername.getText());
                          pstmt.setString(8, jTextFieldstudfatheroccupation.getText());
                          pstmt.setString(9, jTextAreastudaddress.getText());
//                          pstmt.setString(10, jTextFieldstudid.getText());
//                          pstmt.setInt(10, Integer.parseInt(jTextFieldstudid.getText()));
                          pstmt.setInt(10, Integer.parseInt(jTextFieldstudid.getText().trim().replaceAll("[^0-9]","")));

                          pstmt.setString(11,((JTextField)jDateChooserdateofaddmission.getDateEditor().getUiComponent()).getText());
                          String classname="";
                          if(jRadioButton1.isSelected())
                          {
                              classname =jRadioButton1.getText();
                          }
                          if(jRadioButton2.isSelected())
                          {
                              classname =jRadioButton2.getText();
                          }
                          if(jRadioButton3.isSelected())
                          {
                              classname=jRadioButton3.getText();
                          }
                          if(jRadioButton4.isSelected())
                          {
                              classname=jRadioButton4.getText();
                          }
                          pstmt.setString(12, classname);
                          String dept = "";
                          if(jRadioButtonse.isSelected())
                          {
                              dept =jRadioButtonse.getText();
                          }
                          if(jRadioButtoncs.isSelected())
                          {
                              dept =jRadioButtoncs.getText();
                          }
                          if(jRadioButtonit.isSelected())
                          {
                              dept =jRadioButtonit.getText();
                          }
                           pstmt.setString(13, dept);
                          
                          
                          
                          
                         int rs= pstmt.executeUpdate();
                        
                         if(rs>0)
                         {
                            JOptionPane.showMessageDialog(this, "Record succefuly");
                                                   jTextFieldstudfirstname.setText("");
                                                   jTextFieldstudsecondname1.setText("");
                                                   ((JTextField)jDatestuddob.getDateEditor().getUiComponent()).setText("");
                                                   jTextFieldstudcontantno.setText("");
                                                   jTextFieldstudemail.setText("");
                                                   jTextFieldstudfathername.setText("");
                                                   jTextFieldstudfatheroccupation.setText("");
                                                   jTextAreastudaddress.setText("");
                                                   jTextFieldstudid.setText("");
                                                   ((JTextField)jDateChooserdateofaddmission.getDateEditor().getUiComponent()).setText("");
                                                   buttonGroup1.clearSelection();
                                                   buttonGroup2.clearSelection();
                                                   buttonGroup3.clearSelection();
                             
                         }
                         else{
                         JOptionPane.showMessageDialog(this, "error is not come");
                         }
                         pstmt.close();
                         conn.close();
        
        }
        catch(Exception e){
            System.out.println(e);
        
        }
    }//GEN-LAST:event_jButtonstudaddActionPerformed

    private void jButtonstudrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonstudrecordActionPerformed
        // TODO add your handling code here:
        
        Student_info1 student =new Student_info1 ();
        student.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonstudrecordActionPerformed

    private void jRadioButtonseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonseActionPerformed

    private void jRadioButtonmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonmaleActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButtonmaleActionPerformed

    private void jRadioButtonfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonfemaleActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButtonfemaleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButtonstudadd;
    private javax.swing.JButton jButtonstudrecord;
    private com.toedter.calendar.JDateChooser jDateChooserdateofaddmission;
    private com.toedter.calendar.JDateChooser jDatestuddob;
    private javax.swing.JLabel jLabelstudDOB;
    private javax.swing.JLabel jLabelstudaddress;
    private javax.swing.JLabel jLabelstudclassname;
    private javax.swing.JLabel jLabelstudcontantno;
    private javax.swing.JLabel jLabelstuddateofaddmissions;
    private javax.swing.JLabel jLabelstuddepartment;
    private javax.swing.JLabel jLabelstudemail;
    private javax.swing.JLabel jLabelstudfathername;
    private javax.swing.JLabel jLabelstudfatheroccupation;
    private javax.swing.JLabel jLabelstudfirstname;
    private javax.swing.JLabel jLabelstudgender;
    private javax.swing.JLabel jLabelstudid;
    private javax.swing.JLabel jLabelstudsecondname;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelacademicinfo;
    private javax.swing.JPanel jPanelmanagestudents;
    private javax.swing.JPanel jPanelstudbuttons;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButtoncs;
    private javax.swing.JRadioButton jRadioButtonfemale;
    private javax.swing.JRadioButton jRadioButtonit;
    private javax.swing.JRadioButton jRadioButtonmale;
    private javax.swing.JRadioButton jRadioButtonse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreastudaddress;
    private javax.swing.JTextField jTextFieldstudcontantno;
    private javax.swing.JTextField jTextFieldstudemail;
    private javax.swing.JTextField jTextFieldstudfathername;
    private javax.swing.JTextField jTextFieldstudfatheroccupation;
    private javax.swing.JTextField jTextFieldstudfirstname;
    private javax.swing.JTextField jTextFieldstudid;
    private javax.swing.JTextField jTextFieldstudsecondname1;
    // End of variables declaration//GEN-END:variables

    
//    private String gender;
}
