/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author one
 */
public class Manage_Teacher extends javax.swing.JInternalFrame {

    /**
     * Creates new form Manage_Teacher
     */
    public Manage_Teacher() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelmanageteachers = new javax.swing.JPanel();
        jLabelteacherfirstname = new javax.swing.JLabel();
        jTextFieldteacherfirstname = new javax.swing.JTextField();
        jLabelteachersecondname = new javax.swing.JLabel();
        jTextFieldteachersecondname = new javax.swing.JTextField();
        jLabelteacherDOB = new javax.swing.JLabel();
        jDateteacherdob = new com.toedter.calendar.JDateChooser();
        jLabelteachergender = new javax.swing.JLabel();
        jLabelteachercontantno = new javax.swing.JLabel();
        jTextFieldteachercontantno = new javax.swing.JTextField();
        jLabelteacheremail = new javax.swing.JLabel();
        jTextFieldteacheremail = new javax.swing.JTextField();
        jLabeteacherfathername = new javax.swing.JLabel();
        jTextFieldteacherfathername = new javax.swing.JTextField();
        jLabelteacheraddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreateacheraddress = new javax.swing.JTextArea();
        jRadioButtonmale = new javax.swing.JRadioButton();
        jRadioButtonfemale = new javax.swing.JRadioButton();
        jPanelacademicinfoteacher = new javax.swing.JPanel();
        jScrollPaneteachereducation = new javax.swing.JScrollPane();
        jPanelteacteracademic = new javax.swing.JPanel();
        jLabelteacherdesgination = new javax.swing.JLabel();
        jLabeteachersalary = new javax.swing.JLabel();
        jTextFieldteacherslary = new javax.swing.JTextField();
        jLabelteacherid = new javax.swing.JLabel();
        jTextFieldteacherid = new javax.swing.JTextField();
        jLabelteacherdateofjoining = new javax.swing.JLabel();
        jDateChooserdateofjoining = new com.toedter.calendar.JDateChooser();
        jTextFieldteacherdesignation = new javax.swing.JTextField();
        jLabelteacherexperience = new javax.swing.JLabel();
        jLabelteacheruniverstynamedoctrate = new javax.swing.JLabel();
        jLabelteacheruniverstynamepostgraduate = new javax.swing.JLabel();
        jLabelteacherdoctrate = new javax.swing.JLabel();
        jLabelteacherqualification = new javax.swing.JLabel();
        jLabelteacherpostgraduatedegree = new javax.swing.JLabel();
        jLabelteacheruniverstynamegraduate = new javax.swing.JLabel();
        jLabelteacheridgraduadtedegree = new javax.swing.JLabel();
        jTextFieldteacherqualification = new javax.swing.JTextField();
        jTextFieldteacherexperience = new javax.swing.JTextField();
        jTextFieldteachergraduateuniname = new javax.swing.JTextField();
        jTextFieldteacherpostgraduateuniname = new javax.swing.JTextField();
        jTextFieldteacherdoctrateuniname = new javax.swing.JTextField();
        jCheckBoxteachergraduatedegree = new javax.swing.JCheckBox();
        jCheckBoxteacherpostgraduate = new javax.swing.JCheckBox();
        jCheckBoxteacherdoctrate = new javax.swing.JCheckBox();
        jPanelteacherbuttons = new javax.swing.JPanel();
        jButtonteacheradd = new javax.swing.JButton();
        jButtonteacherrecord = new javax.swing.JButton();

        jPanelmanageteachers.setBackground(new java.awt.Color(153, 153, 153));
        jPanelmanageteachers.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Basic Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 36))); // NOI18N

        jLabelteacherfirstname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteacherfirstname.setText("First Name :");

        jTextFieldteacherfirstname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldteacherfirstname.setText(" ");

        jLabelteachersecondname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteachersecondname.setText("Second Name :");

        jTextFieldteachersecondname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldteachersecondname.setText(" ");

        jLabelteacherDOB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteacherDOB.setText("Date of Birth :");

        jDateteacherdob.setDateFormatString("yyyy-MM-dd");

        jLabelteachergender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteachergender.setText("Gender:");

        jLabelteachercontantno.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteachercontantno.setText("Contant No :");

        jTextFieldteachercontantno.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldteachercontantno.setText(" ");

        jLabelteacheremail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteacheremail.setText("Email :");

        jTextFieldteacheremail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldteacheremail.setText(" ");

        jLabeteacherfathername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabeteacherfathername.setText("Father Name :");

        jTextFieldteacherfathername.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldteacherfathername.setText(" ");

        jLabelteacheraddress.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteacheraddress.setText("Address :");

        jTextAreateacheraddress.setColumns(20);
        jTextAreateacheraddress.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextAreateacheraddress.setRows(5);
        jScrollPane1.setViewportView(jTextAreateacheraddress);

        buttonGroup1.add(jRadioButtonmale);
        jRadioButtonmale.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButtonmale.setText("Male");

        buttonGroup1.add(jRadioButtonfemale);
        jRadioButtonfemale.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButtonfemale.setText("Female");

        javax.swing.GroupLayout jPanelmanageteachersLayout = new javax.swing.GroupLayout(jPanelmanageteachers);
        jPanelmanageteachers.setLayout(jPanelmanageteachersLayout);
        jPanelmanageteachersLayout.setHorizontalGroup(
            jPanelmanageteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmanageteachersLayout.createSequentialGroup()
                .addGroup(jPanelmanageteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelmanageteachersLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanelmanageteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelteacherfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelteachergender, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelmanageteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelmanageteachersLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldteacherfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelmanageteachersLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jRadioButtonmale)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonfemale))))
                    .addGroup(jPanelmanageteachersLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabeteacherfathername, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldteacherfathername, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jPanelmanageteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelmanageteachersLayout.createSequentialGroup()
                        .addComponent(jLabelteachersecondname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldteachersecondname, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelmanageteachersLayout.createSequentialGroup()
                        .addComponent(jLabelteachercontantno, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldteachercontantno, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanelmanageteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelmanageteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelmanageteachersLayout.createSequentialGroup()
                            .addComponent(jLabelteacheraddress, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelmanageteachersLayout.createSequentialGroup()
                            .addComponent(jLabelteacheremail, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldteacheremail, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelmanageteachersLayout.createSequentialGroup()
                        .addComponent(jLabelteacherDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDateteacherdob, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanelmanageteachersLayout.setVerticalGroup(
            jPanelmanageteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelmanageteachersLayout.createSequentialGroup()
                .addGroup(jPanelmanageteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelmanageteachersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDateteacherdob, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelmanageteachersLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanelmanageteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelteacherfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldteacherfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelteachersecondname, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldteachersecondname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelteacherDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanelmanageteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelmanageteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelteachergender, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelteachercontantno, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButtonmale)
                        .addComponent(jRadioButtonfemale))
                    .addGroup(jPanelmanageteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldteachercontantno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelteacheremail, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldteacheremail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelmanageteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelmanageteachersLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanelmanageteachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldteacherfathername, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabeteacherfathername, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelmanageteachersLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelteacheraddress, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelmanageteachersLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanelacademicinfoteacher.setBackground(new java.awt.Color(153, 153, 153));
        jPanelacademicinfoteacher.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Academic Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N

        jScrollPaneteachereducation.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPaneteachereducation.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jLabelteacherdesgination.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteacherdesgination.setText("Designation:");

        jLabeteachersalary.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabeteachersalary.setText("      Salary:");

        jTextFieldteacherslary.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldteacherslary.setText(" ");
        jTextFieldteacherslary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldteacherslaryActionPerformed(evt);
            }
        });

        jLabelteacherid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteacherid.setText("Teacher ID:");

        jTextFieldteacherid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldteacherid.setText(" ");
        jTextFieldteacherid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldteacheridActionPerformed(evt);
            }
        });

        jLabelteacherdateofjoining.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteacherdateofjoining.setText("Date Of Joining :");

        jDateChooserdateofjoining.setDateFormatString("yyyy-MM-dd");

        jTextFieldteacherdesignation.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldteacherdesignation.setText(" ");
        jTextFieldteacherdesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldteacherdesignationActionPerformed(evt);
            }
        });

        jLabelteacherexperience.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteacherexperience.setText("Experience :");

        jLabelteacheruniverstynamedoctrate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteacheruniverstynamedoctrate.setText("Universty Name:");

        jLabelteacheruniverstynamepostgraduate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteacheruniverstynamepostgraduate.setText("Universty Name:");

        jLabelteacherdoctrate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteacherdoctrate.setText("Doctrate:");

        jLabelteacherqualification.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteacherqualification.setText("Accademic Qualification :");

        jLabelteacherpostgraduatedegree.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteacherpostgraduatedegree.setText("Postgraduate Degree:");

        jLabelteacheruniverstynamegraduate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteacheruniverstynamegraduate.setText("Universty Name:");

        jLabelteacheridgraduadtedegree.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelteacheridgraduadtedegree.setText("Graduate Degree:");

        jTextFieldteacherqualification.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldteacherqualification.setText(" ");
        jTextFieldteacherqualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldteacherqualificationActionPerformed(evt);
            }
        });

        jTextFieldteacherexperience.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldteacherexperience.setText(" ");
        jTextFieldteacherexperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldteacherexperienceActionPerformed(evt);
            }
        });

        jTextFieldteachergraduateuniname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldteachergraduateuniname.setText(" ");
        jTextFieldteachergraduateuniname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldteachergraduateuninameActionPerformed(evt);
            }
        });

        jTextFieldteacherpostgraduateuniname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldteacherpostgraduateuniname.setText(" ");
        jTextFieldteacherpostgraduateuniname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldteacherpostgraduateuninameActionPerformed(evt);
            }
        });

        jTextFieldteacherdoctrateuniname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldteacherdoctrateuniname.setText(" ");
        jTextFieldteacherdoctrateuniname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldteacherdoctrateuninameActionPerformed(evt);
            }
        });

        jCheckBoxteachergraduatedegree.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBoxteachergraduatedegree.setText(" ");

        jCheckBoxteacherpostgraduate.setText(" ");

        jCheckBoxteacherdoctrate.setText(" ");

        javax.swing.GroupLayout jPanelteacteracademicLayout = new javax.swing.GroupLayout(jPanelteacteracademic);
        jPanelteacteracademic.setLayout(jPanelteacteracademicLayout);
        jPanelteacteracademicLayout.setHorizontalGroup(
            jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelteacteracademicLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelteacteracademicLayout.createSequentialGroup()
                        .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelteacherdesgination, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelteacherid, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldteacherdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldteacherid, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelteacteracademicLayout.createSequentialGroup()
                        .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelteacherqualification, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelteacheridgraduadtedegree, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelteacherpostgraduatedegree, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelteacherdoctrate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxteacherdoctrate)
                            .addComponent(jCheckBoxteacherpostgraduate)
                            .addComponent(jTextFieldteacherqualification, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxteachergraduatedegree, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelteacteracademicLayout.createSequentialGroup()
                        .addComponent(jLabelteacheruniverstynamedoctrate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldteacherdoctrateuniname, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelteacteracademicLayout.createSequentialGroup()
                        .addComponent(jLabelteacheruniverstynamepostgraduate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldteacherpostgraduateuniname, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelteacteracademicLayout.createSequentialGroup()
                        .addComponent(jLabelteacheruniverstynamegraduate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelteacteracademicLayout.createSequentialGroup()
                                .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelteacherexperience, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelteacherdateofjoining)
                                    .addComponent(jLabeteachersalary, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84)
                                .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldteacherslary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooserdateofjoining, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldteacherexperience, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextFieldteachergraduateuniname, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanelteacteracademicLayout.setVerticalGroup(
            jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelteacteracademicLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserdateofjoining, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelteacherid, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldteacherid, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelteacherdateofjoining, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelteacherdesgination, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabeteachersalary, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addComponent(jTextFieldteacherslary))
                    .addComponent(jTextFieldteacherdesignation))
                .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelteacteracademicLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldteacherqualification, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelteacherqualification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelteacheridgraduadtedegree, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxteachergraduatedegree, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelteacteracademicLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldteacherexperience, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jLabelteacherexperience, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelteacteracademicLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldteachergraduateuniname, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelteacteracademicLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelteacheruniverstynamegraduate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)))))
                .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelteacteracademicLayout.createSequentialGroup()
                        .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelteacherpostgraduatedegree, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxteacherpostgraduate))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelteacherdoctrate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxteacherdoctrate)))
                    .addGroup(jPanelteacteracademicLayout.createSequentialGroup()
                        .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelteacheruniverstynamepostgraduate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldteacherpostgraduateuniname, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanelteacteracademicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelteacheruniverstynamedoctrate, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(jTextFieldteacherdoctrateuniname))))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jScrollPaneteachereducation.setViewportView(jPanelteacteracademic);

        javax.swing.GroupLayout jPanelacademicinfoteacherLayout = new javax.swing.GroupLayout(jPanelacademicinfoteacher);
        jPanelacademicinfoteacher.setLayout(jPanelacademicinfoteacherLayout);
        jPanelacademicinfoteacherLayout.setHorizontalGroup(
            jPanelacademicinfoteacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelacademicinfoteacherLayout.createSequentialGroup()
                .addComponent(jScrollPaneteachereducation, javax.swing.GroupLayout.PREFERRED_SIZE, 1082, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanelacademicinfoteacherLayout.setVerticalGroup(
            jPanelacademicinfoteacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneteachereducation, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelteacherbuttons.setBackground(new java.awt.Color(153, 153, 153));

        jButtonteacheradd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonteacheradd.setText("Add New");
        jButtonteacheradd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonteacheradd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonteacheraddActionPerformed(evt);
            }
        });

        jButtonteacherrecord.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonteacherrecord.setText("Professor Record");
        jButtonteacherrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonteacherrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonteacherrecordMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonteacherrecordMousePressed(evt);
            }
        });
        jButtonteacherrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonteacherrecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelteacherbuttonsLayout = new javax.swing.GroupLayout(jPanelteacherbuttons);
        jPanelteacherbuttons.setLayout(jPanelteacherbuttonsLayout);
        jPanelteacherbuttonsLayout.setHorizontalGroup(
            jPanelteacherbuttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelteacherbuttonsLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButtonteacheradd, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 698, Short.MAX_VALUE)
                .addComponent(jButtonteacherrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanelteacherbuttonsLayout.setVerticalGroup(
            jPanelteacherbuttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelteacherbuttonsLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanelteacherbuttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonteacherrecord, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonteacheradd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelacademicinfoteacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelmanageteachers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelteacherbuttons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelmanageteachers, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelacademicinfoteacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelteacherbuttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldteacheridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldteacheridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldteacheridActionPerformed

    private void jTextFieldteacherslaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldteacherslaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldteacherslaryActionPerformed

    private void jTextFieldteacherdesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldteacherdesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldteacherdesignationActionPerformed

    private void jTextFieldteacherqualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldteacherqualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldteacherqualificationActionPerformed

    private void jTextFieldteacherexperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldteacherexperienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldteacherexperienceActionPerformed

    private void jTextFieldteachergraduateuninameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldteachergraduateuninameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldteachergraduateuninameActionPerformed

    private void jTextFieldteacherpostgraduateuninameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldteacherpostgraduateuninameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldteacherpostgraduateuninameActionPerformed

    private void jTextFieldteacherdoctrateuninameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldteacherdoctrateuninameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldteacherdoctrateuninameActionPerformed

    private void jButtonteacherrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonteacherrecordActionPerformed
        // TODO add your handling code here:
        Teacher_Info teacher = new Teacher_Info();
        teacher.setVisible(true);
        this.setVisible(false);
         
    }//GEN-LAST:event_jButtonteacherrecordActionPerformed

    private void jButtonteacheraddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonteacheraddActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection
                     ("jdbc:mysql://localhost:3306/admin_login","root","");
             PreparedStatement pstmte = conn.prepareStatement
                     ("INSERT INTO teacher  values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ");
                          pstmte.setString(1, jTextFieldteacherfirstname.getText());
                          pstmte.setString(2, jTextFieldteachersecondname.getText());
                          pstmte.setString(3, ((JTextField)jDateteacherdob.getDateEditor().getUiComponent()).getText());
                          String gender="";
                          if(jRadioButtonmale.isSelected())
                          {
                              gender =jRadioButtonmale.getText();
                          }
                          if(jRadioButtonfemale.isSelected())
                          {
                              gender =jRadioButtonfemale.getText();
                          }
                          pstmte.setString(4, gender);
                          pstmte.setString(5, jTextFieldteachercontantno.getText());
                          pstmte.setString(6, jTextFieldteacheremail.getText());
                          pstmte.setString(7, jTextFieldteacherfathername.getText());
                          pstmte.setString(8, jTextAreateacheraddress.getText());
//                          pstmte.setString(9, jTextFieldteacherid.getText());
                          pstmte.setInt(9, Integer.parseInt(jTextFieldteacherid.getText().trim().replaceAll("[^0-9]","")));

                          pstmte.setString(10,((JTextField)jDateChooserdateofjoining.getDateEditor().getUiComponent()).getText());
                          pstmte.setString(11, jTextFieldteacherdesignation.getText());
                          pstmte.setString(12, jTextFieldteacherslary.getText());
                          pstmte.setString(13, jTextFieldteacherqualification.getText());
                          pstmte.setString(14, jTextFieldteacherexperience.getText());
                          pstmte.setString(15, jTextFieldteachergraduateuniname.getText());
                          pstmte.setString(16, jTextFieldteacherpostgraduateuniname.getText());
                          pstmte.setString(17, jTextFieldteacherdoctrateuniname.getText());
                           int rs= pstmte.executeUpdate();
                        
                         if(rs>0)
                         {
                            JOptionPane.showMessageDialog(this, "Record succefuly");
                          jTextFieldteacherfirstname.setText("");
                          jTextFieldteachersecondname.setText("");
                          ((JTextField)jDateteacherdob.getDateEditor().getUiComponent()).setText("");
                          jTextFieldteachercontantno.setText("");
                          jTextFieldteacheremail.setText("");
                          jTextFieldteacherfathername.setText("");
                          jTextAreateacheraddress.setText("");
                          jTextFieldteacherid.setText("");
                          ((JTextField)jDateChooserdateofjoining.getDateEditor().getUiComponent()).setText("");
                          jTextFieldteacherdesignation.setText("");
                          jTextFieldteacherslary.setText("");
                          jTextFieldteacherqualification.setText("");
                          jTextFieldteacherexperience.setText("");
                          jTextFieldteachergraduateuniname.setText("");
                          jTextFieldteacherpostgraduateuniname.setText("");
                          jTextFieldteacherdoctrateuniname.setText("");
                          buttonGroup1.clearSelection();
                            
                             
                         }
                         else{
                         JOptionPane.showMessageDialog(this, "error is not come");
                         }
                         pstmte.close();
                         conn.close();
        
                          
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonteacheraddActionPerformed

    private void jButtonteacherrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonteacherrecordMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButtonteacherrecordMouseClicked

    private void jButtonteacherrecordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonteacherrecordMousePressed
        // TODO add your handling code here:
//         this.dispose();
//        Teacher_Info teacher =new Teacher_Info();
//        teacher.setVisible(true);
    }//GEN-LAST:event_jButtonteacherrecordMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonteacheradd;
    private javax.swing.JButton jButtonteacherrecord;
    private javax.swing.JCheckBox jCheckBoxteacherdoctrate;
    private javax.swing.JCheckBox jCheckBoxteachergraduatedegree;
    private javax.swing.JCheckBox jCheckBoxteacherpostgraduate;
    private com.toedter.calendar.JDateChooser jDateChooserdateofjoining;
    private com.toedter.calendar.JDateChooser jDateteacherdob;
    private javax.swing.JLabel jLabelteacherDOB;
    private javax.swing.JLabel jLabelteacheraddress;
    private javax.swing.JLabel jLabelteachercontantno;
    private javax.swing.JLabel jLabelteacherdateofjoining;
    private javax.swing.JLabel jLabelteacherdesgination;
    private javax.swing.JLabel jLabelteacherdoctrate;
    private javax.swing.JLabel jLabelteacheremail;
    private javax.swing.JLabel jLabelteacherexperience;
    private javax.swing.JLabel jLabelteacherfirstname;
    private javax.swing.JLabel jLabelteachergender;
    private javax.swing.JLabel jLabelteacherid;
    private javax.swing.JLabel jLabelteacheridgraduadtedegree;
    private javax.swing.JLabel jLabelteacherpostgraduatedegree;
    private javax.swing.JLabel jLabelteacherqualification;
    private javax.swing.JLabel jLabelteachersecondname;
    private javax.swing.JLabel jLabelteacheruniverstynamedoctrate;
    private javax.swing.JLabel jLabelteacheruniverstynamegraduate;
    private javax.swing.JLabel jLabelteacheruniverstynamepostgraduate;
    private javax.swing.JLabel jLabeteacherfathername;
    private javax.swing.JLabel jLabeteachersalary;
    private javax.swing.JPanel jPanelacademicinfoteacher;
    private javax.swing.JPanel jPanelmanageteachers;
    private javax.swing.JPanel jPanelteacherbuttons;
    private javax.swing.JPanel jPanelteacteracademic;
    private javax.swing.JRadioButton jRadioButtonfemale;
    private javax.swing.JRadioButton jRadioButtonmale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneteachereducation;
    private javax.swing.JTextArea jTextAreateacheraddress;
    private javax.swing.JTextField jTextFieldteachercontantno;
    private javax.swing.JTextField jTextFieldteacherdesignation;
    private javax.swing.JTextField jTextFieldteacherdoctrateuniname;
    private javax.swing.JTextField jTextFieldteacheremail;
    private javax.swing.JTextField jTextFieldteacherexperience;
    private javax.swing.JTextField jTextFieldteacherfathername;
    private javax.swing.JTextField jTextFieldteacherfirstname;
    private javax.swing.JTextField jTextFieldteachergraduateuniname;
    private javax.swing.JTextField jTextFieldteacherid;
    private javax.swing.JTextField jTextFieldteacherpostgraduateuniname;
    private javax.swing.JTextField jTextFieldteacherqualification;
    private javax.swing.JTextField jTextFieldteachersecondname;
    private javax.swing.JTextField jTextFieldteacherslary;
    // End of variables declaration//GEN-END:variables
}
